# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

print ('@@@@@  @      @  @@     @       @')
print ('    @  @      @  @ @    @      @ @')
print ('    @  @      @  @  @   @     @   @')
print ('    @  @      @  @   @  @    @@@@@@@')
print ('   @   @      @  @    @ @   @       @')
print ('  @      @@@@    @     @@  @         @')

angka_awal = int(input("Masukkan angka awal: "))
angka_akhir = int(input("Masukkan angka akhir: "))

if angka_awal > angka_akhir:
    angka_awal, angka_akhir = angka_akhir, angka_awal

i = angka_awal
j = angka_akhir

while i < j:
    print(f"{i} | {j}")
    i += 1
    j -= 1

print ('@@@@@  @      @  @@     @       @')
print ('    @  @      @  @ @    @      @ @')
print ('    @  @      @  @  @   @     @   @')
print ('    @  @      @  @   @  @    @@@@@@@')
print ('   @   @      @  @    @ @   @       @')
print ('  @      @@@@    @     @@  @         @')

total_harga = float(input("Total harga belanjaan: "))
jumlah_uang = float(input("Jumlah uang yang diberikan: "))
kembalian = jumlah_uang - total_harga
lembar_uang = [100000, 50000, 20000, 10000, 5000, 2000, 1000, 500, 200, 100]
jumlah_lembar_uang = {}

for nilai_uang in lembar_uang:
    if kembalian >= nilai_uang:
        jumlah = kembalian // nilai_uang
        kembalian -= jumlah * nilai_uang
        jumlah_lembar_uang[nilai_uang] = jumlah

print("Kembalian:", jumlah_uang - total_harga, "Rupiah")
print("Lembar uang yang diperlukan:")

for nilai_uang in lembar_uang:
    if nilai_uang in jumlah_lembar_uang:
        print(f"{nilai_uang} Rupiah:", jumlah_lembar_uang[nilai_uang])